### PR TITLE
Redirect always to whitelisted path after login

### PR DESCRIPTION
**Pull request by zanitete**
The original requested URL is stored by the OIDC lua plugin https://github.com/zmartzone/lua-resty-openidc/

### CODE REVIEW

**Review by smrtl — APPROVED** [review]
mmkay ... so if we login from some nested path, the login is not gonna fail and we will be redirected to the registered callback path ?

**Comment by zanitete** [comment]
yeah, here's the magic: https://github.com/zmartzone/lua-resty-openidc/blob/master/lib/resty/openidc.lua#L369

**Comment by smrtl** [comment]
> yeah, here's the magic: https://github.com/zmartzone/lua-resty-openidc/blob/master/lib/resty/openidc.lua#L369

Ah thanks! But what is answering at `/cb` ? Is it a part of the openidc plugin ?

**Comment by zanitete** [comment]
nope, here's the other magic 😂 
https://github.com/nagra-insight/kong-chart/pull/7

the callback is intercepted by the openidc plugin here: https://github.com/zmartzone/lua-resty-openidc/blob/master/lib/resty/openidc.lua#L1407

basically, the /cb endpoint is never reached but we need a route to avoid a "no route" error from Kong

**Comment by smrtl** [comment]
> nope, here's the other magic 😂
> [nagra-insight/kong-chart#7](https://github.com/nagra-insight/kong-chart/pull/7)

Ah yes, the ingress with no HTTP rule :joy:
So basically openidc intercepts the requests to `/cb` and does some magic ✨

**Pull request merged**
